### ISSUE TITLE
Filter out archived and non-public profiles for faculty-picker

### ISSUE THREAD

**Issue by betsyecastro** [utdal/profiles#104]
In a related ticket, looks like the faculty-picker needs to respect archived and filter out non-public profiles.

![9a30a918-a0eb-45d3-b3ec-8bd67732f0ff](https://user-images.githubusercontent.com/5490820/205163676-eee87767-c986-46a8-934f-3e1979ec6447.jpg)

**Comment by wunc** [comment]
Resolved in #135

**Comment by wunc** [comment]
Resolved in #135
