### ISSUE TITLE
Layout overflow causing horizontal scroll on all pages

### ISSUE THREAD

**Issue by betsyecastro** [utdal/profiles#105]
I was able to reproduce the issue only in production on my 13in Macbook Air, because when I extend my local environment to that screen, none of the resolution options available when extending the screen allow me to see the page exactly as the Macbook Air does it. 

However, I spent a while inspecting the css styles that are present in all the pages, and one thing I noticed is that the footer has full_with class:

```
.full_width {
    width: 100vw;
    position: relative;
    left: 50%;
    margin-left: -50vw;
    padding: 5px 10px 30px;
}
```
Reducing the width to 99vw causes the scrollbar to disappear but of course it cuts off the footer, I'm not sure if this is the best approach to correct this.

**Comment by betsyecastro** [comment]
Changing the position from relative to sticky seems to solve the issue. Sticky adjusts dynamically the element between relative and fixed. I read that the element stays relative until it reaches an offset position in the viewport and gets fixed or "sticked". I can commit the change to test it on staging, would you like me to move forward @wunc ?

**Comment by wunc** [comment]
@betsyecastro I was finally able to reproduce this by changing the macOS setting to "show scroll bars: always". I think the issue is more that `width: 100vw`. I guess the width of the scrollbar isn't taken into account when using 'vw' units. I'll comment more on your PR.

**Comment by gab3** [comment]
Maybe it's Ventura-related? I am seeing it without that setting enabled:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/5191206/205749336-eaa007b1-cf40-4ed6-bd49-d00e6094b4e8.png">

**Comment by wunc** [comment]
@gab3 can you share the exact dimensions & browser when you see it? I wasn't able to reproduce this in Chrome, Firefox, or Safari at any page width that I tried on my computer.

**Comment by betsyecastro** [comment]
Either changing the position property from relative to sticky, or removing the class for the elements makes the scrollbar go away, I tested it on my 13in MacBook Air with Ventura (2560 × 1600).

**Comment by gab3** [comment]
We discovered it appears to be related to having a mouse USB dongle attached to my monitor. I recall at some point not having scrollbars unless scrolling, so am not sure if this is a new default to Ventura or my settings changed another way.

Manually setting it to "When scrolling" causes the vertical and horizontal bars to both go away.
