### ISSUE TITLE
Fix duplicate tags in student form

### ISSUE THREAD

**Issue by wunc** [utdal/profiles#130]
Need to investigate how this happened:

<img width="1167" alt="Screenshot 2023-09-28 at 6 10 55 PM" src="https://github.com/utdal/profiles/assets/11369963/64c7bc5a-8fd8-4e82-a149-4670c2ea2cc6">

**Comment by wunc** [comment]
This seems to only happen when you have multiple schools selected on the form.

To reproduce:

1. Edit a student application and select 2 schools
2. Select a tag

The tag will show as selected once, but two entries will be added in the pivot for it. This effect also seems to multiply when you select and deselect more tags.

**Comment by betsyecastro** [comment]
I'm looking into this as well. It looks like the duplication doesn't occur until the application form gets submitted... At least in for what I've seen.

**Comment by wunc** [comment]
@betsyecastro I figured it out and fixed it. Deployed and manually fixed that one student that had all the duplicate tags.
