### ISSUE TITLE
Create a student application logo

### ISSUE THREAD

**Issue by wunc** [utdal/profiles#24]
Create a logo / badge that faculty can put on their websites that will point back to the application page.

**Comment by alyssa932** [comment]
I didn't get a chance to share these at collab time. Are any of these on the right track
![icons2](https://user-images.githubusercontent.com/17996578/163268192-cb8ea60a-d02c-4b38-841f-34b1c6676e7a.png)

**Comment by gab3** [comment]
@alyssa932 - thanks for drafting. Out of these, I think I like the first one the most, just because I'd err away from a graduation caps or anything that might confuse students about being related to graduation or "applying to graduate" which is a thing.

In my head, I was originally kinda picturing a call to action similar to a "vote now" or "submit now" type of feeling.

This is a mockup I did a while back - I dislike the icon itself, but maybe the typography/layout might inspire. A google of "Apply Now" on image search also provides some interesting options. Thoughts? 

Thanks.

![Asset 4@6x](https://user-images.githubusercontent.com/5191206/163280453-0e01d19c-f3cf-440e-86c8-cf2301f037c7.png)

**Comment by wunc** [comment]
@alyssa932 I think the wording needs to be explicit, i.e. what are they applying for? (It's to join a research group/lab as an undergraduate researcher). For the icon, I like the form, but maybe include something researchy? Is a flask too common? Maybe a microscope?

**Comment by alyssa932** [comment]
Thank you for the quick feedback! I should have mentioned I could change out the icons (I wasn't sure about the grad cap icon either) but was just thinking of the overall shape and badge styles. I will approach with a fresh eye tomorrow. I have some other ideas and this info helps a lot.

**Comment by gab3** [comment]
Ah, gotcha - then I do like the overall shape/colors on the third one as well. I had thought about flask, @wunc, but figured it may be too on the nose since we're also trying to promote non/benchtop science, but maybe if paired with a computer or calculator/survey? 

Just brainstorming - curious to see how this develops, @alyssa932!

**Comment by alyssa932** [comment]
I can change colors, or whatever, but here are two versions of my concept from the inspiration I received
![undergraduateAppLogo_v2](https://user-images.githubusercontent.com/17996578/163602819-a58a29c1-fb2b-457f-be7b-0cbab993256d.png)
.

**Comment by wunc** [comment]
@alyssa932 Can you update the wording and also do the non-badge version, as we discussed? Thanks!

**Comment by alyssa932** [comment]
Here are a couple of ways I played around with the non-badge and another version of the badge
![undergraduateResearchLogos](https://user-images.githubusercontent.com/17996578/167174875-03e85534-1d4b-455c-8304-9079624cd057.png)
.

**Comment by wunc** [comment]
@alyssa932 For the first one (the hexagon), I think I prefer the previous rounded one. Can you just update the rounded one with the new wording? A polygonal shape reminds me of a warning, like a stop-sign or yield sign.

For the second and third, I think the wording needs to be at least as prominent than the icon, i.e. equal height similar to Gabe's initial mockup, since the words carry more clear meaning than the icon.

Also, can you upload just the icon itself here? I'm sure some faculty might prefer to use that along with their own wording on their websites.

**Comment by alyssa932** [comment]
@wunc Here's the next iterations. I am uploading the icon itself in PNG and SVG formats. I did another version of the logo in black and white and color
![undergradResearchIcons](https://user-images.githubusercontent.com/17996578/167201270-8e19dc87-c5e5-4ae1-9959-cbccd5bc6e69.png)
![circularURlogo](https://user-images.githubusercontent.com/17996578/167201279-ebafbeb7-d5a0-47aa-a1f7-6720d237cec6.png)

![undergradResearchIcons](https://user-images.githubusercontent.com/17996578/167201299-85126f3e-0915-409a-8bbc-5b53bf30a7c9.png)
![undergradResearchIcons](https://user-images.githubusercontent.com/17996578/167201314-34f00f95-3946-4306-bbcb-68e483fa997a.svg).

**Comment by alyssa932** [comment]
@wunc The logos looked small so here they are in a separate comment.
![applyNow_v1](https://user-images.githubusercontent.com/17996578/167201536-626785e5-43ef-4e4c-ba30-af869657dc56.png)

**Comment by alyssa932** [comment]
The bottom ones got a little lost. Here are larger versions
![largerLogos](https://user-images.githubusercontent.com/17996578/167205405-7ac22477-1b70-4d73-afa0-ff9714ec25a8.png).

**Comment by alyssa932** [comment]
Updated logos.
![greenBadgeIconFinal](https://user-images.githubusercontent.com/17996578/167481592-c7bcf4ea-4c02-4e0d-a343-e2f268cd1e44.png)
![blackBadgeIconFinal](https://user-images.githubusercontent.com/17996578/167481593-1e5e6220-3803-44c9-9763-decd94a07b68.png)
![undergradResearchBadge8](https://user-images.githubusercontent.com/17996578/167481595-aaf4c174-19f5-4447-857a-da249dd9cfb2.png)

**Comment by alyssa932** [comment]
@gab3 @wunc I will do the header images, too, but is this okay for the icon part? If not, I can keep working on other options
![undergradResearchBadge9](https://user-images.githubusercontent.com/17996578/168296411-bf100d60-a0ed-43be-a741-a1bd35fc6331.png).

**Comment by alyssa932** [comment]
@wunc @gab3 I thought I would try one more version of this. Happy to share it with the team later.
![undergradResearchBadge10](https://user-images.githubusercontent.com/17996578/169062223-808fa363-ec49-48a3-b4a3-d5d966cce9cc.png)

**Comment by wunc** [comment]
@alyssa932 I'm going to go ahead and close this out as completed. We'll share these logos as we roll this out to more schools. Thanks for your work on this.
