### ISSUE TITLE
Ability to delete or archive profiles

### ISSUE THREAD

**Issue by wunc** [utdal/profiles#38]
Maybe a soft delete?

**Comment by betsyecastro** [comment]
A migration was created to add the deleted_at column for soft deleting to the profiles table. Currently testing the trashed() method.

**Comment by betsyecastro** [comment]
It's working!
<img width="1496" alt="Screen Shot 2022-04-27 at 4 36 11 PM" src="https://user-images.githubusercontent.com/5490820/165635147-67a4eb34-5983-440a-9d53-72069135f379.png">

**Comment by betsyecastro** [comment]
Added delete button to Profile edit view
Modified Migration modified to add soft delete feature to the ProfileStudent and ProfileData models
Route profiles.delete
Delete action in Profiles Controller

**Comment by betsyecastro** [comment]
A way to view/restore deleted profiles - Should this feature list the deleted profiles and allow only an admin to restore them @wunc?

**Comment by wunc** [comment]
> A way to view/restore deleted profiles - Should this feature list the deleted profiles and allow only an admin to restore them @wunc?

@betsyecastro I think maybe we can add a filter to the profiles.table view to show/hide the archived profiles (hidden by default). Then the new action button can be: "archive" (if it's active) or "restore" (if it's already archived).

**Comment by betsyecastro** [comment]
Draft PR #61 was created. 

Still working on: 
- Adding the archive option to the profile show view 
- Removing the link to the profile show on the slug from the index view if the record is archived. 

@wunc
