### ISSUE TITLE
Add Profile Summary field to information section to profile, with a specific limit of characters allowed.

### ISSUE THREAD

**Issue by betsyecastro** [utdal/profiles#58]

**Comment by betsyecastro** [comment]
@wunc what's the character limit for this field?

**Comment by wunc** [comment]
@betsyecastro I think my initial thought was the same max length as a Twitter tweet (i.e. 280 characters). I don't think we need a Livewire component for it. We can just use regular HTML5 validation for the front-end and for back-end validation, you should be able to edit the [ProfileUpdateRequest.php](https://github.com/utdal/profiles/blob/develop/app/Http/Requests/ProfileUpdateRequest.php) file.
