### ISSUE TITLE
Staging env testing: Preview emails -> Review Students generates the "Class "Faker\Factory" not found error

### ISSUE THREAD

**Issue by betsyecastro** [utdal/profiles#66]
https://ordev.utdallas.edu/profiles/testing/email-preview/reviewstudents?name=Test%20User

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/5490820/173152713-873a6aa8-eb11-41a8-8873-b9ef0e2d9b8b.png">

**Comment by wunc** [comment]
@betsyecastro this is because the deploy script doesn't install dev dependencies. I've manually installed them for now, but I'll update the script for staging deploys.
